### ISSUE TITLE
Module not working with Magento REST API

### ISSUE THREAD

**Issue by bheindl** [leonex-internet-gmbh/rmp-magento2-extension#2]
When creating an order through magento REST API, the setting of the shipping and billing address fails with this error message:

Missing required argument $name of Leonex\RiskManagementPlatform\Model\Logger

DI configuration for Leonex\RiskManagementPlatform\Model\Logger is only made in frontend scope. Please provide an di configuration for the logger also in the other scopes like webapi_rest (or a default one).

**Comment by stollr** [comment]
Have you executed `php bin/magento setup:di:compile` after the installation of the module?

**Comment by bheindl** [comment]
Yes, I do. Actually we also get the same error, when creating an order through magento backend. Logger configuration is also missing there.

**Comment by stollr** [comment]
Okay, I think we have fixed the issue. Can you please test with v2.2.1?

**Comment by naitsirch** [comment]
Closed due to missing feedback.

**Comment by stollr** [comment]
Closed issue due to missing feedback.
