### ISSUE TITLE
Deprecated method Leonex\RiskManagementPlatform\Model\Component\Quote::getQuoteId() is called from Leonex\RiskManagementPlatform\Model\Component\Connector::loadCachedResponse()

### ISSUE THREAD

**Issue by bheindl** [leonex-internet-gmbh/rmp-magento2-extension#3]
The mentioned method was deprecated in version 2.4.1 but is still called within the connector and leading to error as $this->quote is not necessarily populated with the full quote.

Suggested fix:

Remove quote id logging from Leonex\RiskManagementPlatform\Model\Component\Connector line 247.

**Comment by stollr** [comment]
Thanks four your hint. We have addresses this issue in 2.4.2. Feel free to update.

**Comment by bheindl** [comment]
@stollr Thank you very much, updated to 2.4.2!
